# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d05c98b25e425af3d4c28ea527db4c30554f4b65ef94b0506a4bae1e8574116377f9e33472d95e3ce85c024b07d8831d7606a1b5445902ea9f2e6cad8477810

test:
  secret_key_base: ca889723bd758a17442b79835e4583cc4af0d37b49f3b783e9485f4ee0aad649f714cad4ca071a08368d01feb6d626587063ef8466f5e17e2a21a0e12245f64c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
